package com.marcusprado02.sharedkernel.infrastructure.sms.model;

public enum SmsErrorCode {
    NONE, NETWORK, TIMEOUT, RATE_LIMIT, AUTHENTICATION, AUTHORIZATION,
    INVALID_NUMBER, CARRIER_BLOCKED, CONTENT_VIOLATION, OPT_OUT, DUPLICATE,
    PROVIDER_UNAVAILABLE, VALIDATION, UNKNOWN
}
